export type Category = "Activity" | "Place" | "Other";

// Single source of truth for the category list (nav bar, form dropdown).
export const CATEGORIES: Category[] = ["Activity", "Place", "Other"];

export type Bucket = {
  id: string;
  headline: string;
  category: Category;
  link?: string;
  description: string;
  done: boolean;
  doneDate?: string; // ISO date, e.g. "2026-07-31"
};

// Everything the caller provides when writing a bucket. `id` is generated by
// the hook, and `done` is derived from `doneDate` by the business rule.
export type BucketInput = Omit<Bucket, "id" | "done">;
